server:
  port: 5555
  servlet:
    context-path: /auth-service/api/v1

spring:
  application:
    name: auth-service

  datasource:
    url: ${SERVER_DATASOURCE_URL}
    username: ${SERVER_DATASOURCE_USERNAME}
    password: ${SERVER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${SERVER_DATASOURCE_MAXIMUM_POOL_SIZE}
      minimum-idle: ${SERVER_DATASOURCE_MINIMUM_IDLE}
      connection-timeout: ${SERVER_DATASOURCE_CONNECTION_TIMEOUT}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SERVER_DATASOURCE_DDL}
    show-sql: true

app:
  jwt:
    secret:
      key: ${SERVER_JWT_SECRET_KEY}
    access:
      token:
        expiration: ${SERVER_JWT_ACCESS_TOKEN_EXPIRATION}
    refresh:
      token:
        expiration: ${SERVER_JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO