server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: ${BASE_URL_AUTH_SVC}
            predicates:
              - Path=/api/v1/auth,/api/v1/logout,/api/v1/refresh-token
          - id: user-service
            uri: ${BASE_URL_USER_SVC}
            predicates:
              - Path=/api/v1/user/**
          - id: project-service
            uri: ${BASE_URL_PROJECT_SVC}
            predicates:
              - Path=/api/v1/projects/**
          - id: task-service
            uri: ${BASE_URL_TASK_SVC}
            predicates:
              - Path=/api/v1/tasks/**
          - id: notification-service
            uri: ${BASE_URL_NOTIFICATION_SVC}
            predicates:
              - Path=/api/v1/notifications/**