server:
  port: 1111

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/workflow_management?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${SERVER_DATASOURCE_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${SERVER_DATASOURCE_MINIMUM_IDLE:5}
      connection-timeout: ${SERVER_DATASOURCE_CONNECTION_TIMEOUT:180000}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SERVER_DATASOURCE_DDL:none}
    show-sql: true

  data:
    redis:
      host: ${SERVER_REDIS_HOST}
      port: ${SERVER_REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SERVER_EMAIL_USERNAME:animeshop2462@gmail.com}
    password: ${SERVER_EMAIL_PASSWORD:yewnokvitnurtcsa}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  mail:
    from: ${SERVER_EMAIL_FROM:animeshop2462@gmail.com}

jwt:
  secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
  expiration-ms: 86400000

logging:
  level:
    root: INFO