server:
  port: 1111

spring:
  application:
    name: user-service

  datasource:
    url: ${SERVER_DATASOURCE_URL}
    username: ${SERVER_DATASOURCE_USERNAME}
    password: ${SERVER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${SERVER_DATASOURCE_MAXIMUM_POOL_SIZE}
      minimum-idle: ${SERVER_DATASOURCE_MINIMUM_IDLE}
      connection-timeout: ${SERVER_DATASOURCE_CONNECTION_TIMEOUT}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SERVER_DATASOURCE_DDL}
    show-sql: true

  data:
    redis:
      host: ${SERVER_REDIS_HOST}
      port: ${SERVER_REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SERVER_EMAIL_USERNAME}
    password: ${SERVER_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  mail:
    from: ${SERVER_EMAIL_FROM}

logging:
  level:
    root: INFO