server:
  port: 2222

spring:
  application:
    name: project-service

  datasource:
    url: ${SERVER_DATASOURCE_URL}
    username: ${SERVER_DATASOURCE_USERNAME}
    password: ${SERVER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${SERVER_DATASOURCE_MAXIMUM_POOL_SIZE}
      minimum-idle: ${SERVER_DATASOURCE_MINIMUM_IDLE}
      connection-timeout: ${SERVER_DATASOURCE_CONNECTION_TIMEOUT}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SERVER_DATASOURCE_DDL}
    show-sql: true

logging:
  level:
    root: INFO